### PR TITLE
cplp -1022 - remove forbidden for no status update.

### PR DESCRIPTION
**Pull request by Akshay-Chaudhari-BMW**
remove forbidden for no status update.

### CODE REVIEW

**Comment by jjeroch** [comment]
@Akshay-Chaudhari-BMW  I can see that you removed the exception. However doesn't this result now still in an issue if the invitation status is PENDING, ACCEPTED and DECLINED

**Review by jjeroch — COMMENTED** [review]
@Akshay-Chaudhari-BMW I can see that you removed the exception. However doesn't this result now still in an issue if the invitation status is PENDING, ACCEPTED and DECLINED

**Comment by Akshay-Chaudhari-BMW** [comment]
> @Akshay-Chaudhari-BMW I can see that you removed the exception. However doesn't this result now still in an issue if the invitation status is PENDING, ACCEPTED and DECLINED

@jjeroch If there is no status update then response will be empty body.

**Comment by jjeroch** [comment]
As just discussed we update it as following "if status is "2" (PENDING) we will update the invitation status to "3" (ACCEPTED); if status is "1", "3" or "4" we send back an empty body"

**Comment by Akshay-Chaudhari-BMW** [comment]
Invitation status update done

**Review by jjeroch — APPROVED** [review]
Looks good, approved

**Pull request merged**
