### PR TITLE
feature/cplp 831 post app consent

### PR DESCRIPTION
**Pull request by qxz2mqe**
https://jira.catena-x.net/browse/CPLP-831

### CODE REVIEW

**Comment by ntruchsess** [comment]
@qxz2mqe As #196 also contains a new Migration I'll review this PR as soon #196 is merged in main and into this branch and then the Migration in this PR is recreated based on latest DBContext from #196

**Comment by ntruchsess** [comment]
PR #196 is merged, please pull main, resolve the conflicts and recreate the migration.

**Review by ntruchsess — CHANGES_REQUESTED** [review]
PR https://github.com/catenax-ng/product-portal-backend/pull/196 is merged, please pull main, resolve the conflicts and recreate the migration.

**Comment by qxz2mqe** [comment]
@ntruchsess  I demonstrated the feature to Julia. It is working as expected. Additional Item for linking the respective agreements to the offerTypeId (suggested table name would be agreement_assigned_offer_ids / AgreementAssignedOfferIds can be taken into upcoming sprint. Please review the PR

**Review by ntruchsess — APPROVED** [review]
@qxz2mqe @jjeroch  I did implement the discussed change from AgreementCategoryId to OfferTypeId adding table agreement_assigned_offer_type recreating the migration. From my point of view the PR is ready to merge.

**Comment by ntruchsess** [comment]
migration applied to local devenv in https://github.com/tractusx-team-portal-onboarding/devenv/pull/132

**Comment by ntruchsess** [comment]
@qxz2mqe : 
you wrote:
>'I demonstrated the feature to Julia. It is working as expected'.

I have no idea what you did demonstrate, but apparently it was not the creation of a consent by calling /api/apps/AppReleaseProcess/consent/{appId}/OfferAgreementConsents and subsequently getting the newly created consent via /api/apps/AppReleaseProcess/consent/{appId}

The get-endpoint does correctly access consent_assigned_offer-table while the POST-endpoint does not create an entry in there

https://github.com/catenax-ng/product-portal-backend/blob/e9ea8fe56ced0cf4696e2729dc613bc35a954750/src/marketplace/CatenaX.NetworkServices.Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs#L270

your code is missing this line:
https://github.com/catenax-ng/product-portal-backend/blob/ca4cded659db409d13cc16a9eeb0f21b9aa41af4/src/marketplace/CatenaX.NetworkServices.Offers.Library/Service/OfferService.cs#L161

**Pull request merged**
